words = [
        ['you','okay'],
        ['you',
        'okay'],
        ['you',
        'okay'],
        ['you',
        'okay'],
        ['you',
        'okay'],
        ['good',
        'morning'],
        ['good',
        'morning'],
        ['good',
        'morning'],
        ['good',
        'morning'],
        ['good',
        'morning'],
        ['good',
        'morning'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['how',
        'you'],
        ['old',
        'you'],
        ['old',
        'you'],
        ['old',
        'you'],
        ['old',
        'you'],
        ['old',
        'you'],
        ['old',
        'you'],
        ['old',
        'you'],
        ['i',
        'like',
        'you'],
        ['i',
        'like',
        'you'],
        ['i',
        'like',
        'you'],
        ['i',
        'like',
        'you'],
        ['i',
        'like',
        'you'],
        ['im',
        'fine'],
        ['im',
        'fine'],
        ['im',
        'fine'],
        ['im',
        'fine'],
        ['im',
        'fine'],
        ['im',
        'fine'],
        ['im',
        'fine'],
        ['eat'],
        ['eat'],
        ['eat'],
        ['eat'],
        ['where',
        'you',
        'from'],
        ['where',
        'you',
        'from'],
        ['where',
        'you',
        'from'],
        ['where',
        'you',
        'from']
        ]
locations = [
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 1\\You 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 1\\Okay 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 2\\You 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 2\\Okay 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 3\\You 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 3\\Okay 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 4\\You 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 4\\Okay 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 5\\You 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Are you okay\\You Okay 5\\Okay 5.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 1\\Good 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 1\\Morning 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 2\\Good 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 2\\Morning 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 3\\Good 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 3\\Morning 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 4\\Good 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 4\\Morning 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 5\\Good 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 5\\Morning 5.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 6\\Good 6.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Good Morning\\Good Morning 6\\Morning 6.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 1\\How 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 1\\You 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 2\\How 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 2\\You 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 3\\How 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 3\\You 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 4\\How 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 4\\You 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 5\\How 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 5\\You 5.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 6\\How 6.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 6\\You 6.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 7\\How 7.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 7\\You 7.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 8\\How 8.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 8\\You 8.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 9\\How 9.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How are you\\How You 9\\You 9.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 1\\Old.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 1\\You.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 2\\Old 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 2\\You 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 3\\Old 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 3\\You 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 4\\Old 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 4\\You 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 5\\Old 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 5\\You 5.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 6\\Old 6.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 6\\You 6.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 7\\Old 7.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\How old are you\\Old You 7\\You 7.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 1\\I 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 1\\Like 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 1\\You 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 2\\I 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 2\\Like 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 2\\You 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 3\\I 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 3\\Like 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 3\\You 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 4\\I 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 4\\Like 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 4\\You 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 5\\I 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 5\\Like 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I like you\\I Like You 5\\You 5.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\I\'m Fine 1\\Im 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\I\'m Fine 1\\Fine 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 2\\Im 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 2\\Fine 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 3\\Im 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 3\\Fine 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 4\\Im 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 4\\Fine 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 5\\Im 5.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 5\\Fine 5.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 6\\Im 6.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 6\\Fine 6.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 7\\Im 7.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\I\'m fine\\Im Fine 7\\Fine 7.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Let\'s eat\\Eat 1\\Eat 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Let\'s eat\\Eat 2\\Eat 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Let\'s eat\\Eat 3\\Eat 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Let\'s eat\\Eat 4\\Eat 4.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 1\\Where 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 1\\You 1.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 1\\From 1.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 2\\Where 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 2\\You 2.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 2\\From 2.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 3\\Where 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 3\\You 3.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 3\\From 3.mp4'],
        ['D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 4\\Where 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 4\\You 4.mp4',
        'D:\\Users\\JanlofreDy\\Desktop\\American Sign Language Translator Prototype\\Development Trial\\Sign Language Videos\\Where are you from\\Where You From 4\\From 4.mp4'],
        ]